# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(950, 700))
        MainWindow.setMaximumSize(QtCore.QSize(15001, 15000))
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(950, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1500000, 1500000))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(949, 600))
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 75)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_title = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setMinimumSize(QtCore.QSize(0, 0))
        self.label_title.setMaximumSize(QtCore.QSize(950, 70))
        self.label_title.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setOpenExternalLinks(False)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label_imgTitle = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_imgTitle.sizePolicy().hasHeightForWidth())
        self.label_imgTitle.setSizePolicy(sizePolicy)
        self.label_imgTitle.setMinimumSize(QtCore.QSize(290, 290))
        self.label_imgTitle.setMaximumSize(QtCore.QSize(290, 290))
        self.label_imgTitle.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_imgTitle.setText("")
        self.label_imgTitle.setPixmap(QtGui.QPixmap("21_manual1.gif"))
        self.label_imgTitle.setScaledContents(True)
        self.label_imgTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imgTitle.setObjectName("label_imgTitle")
        self.verticalLayout.addWidget(self.label_imgTitle, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.label_question = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_question.sizePolicy().hasHeightForWidth())
        self.label_question.setSizePolicy(sizePolicy)
        self.label_question.setMaximumSize(QtCore.QSize(200, 30))
        self.label_question.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_question.setScaledContents(False)
        self.label_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question.setObjectName("label_question")
        self.verticalLayout.addWidget(self.label_question, 0, QtCore.Qt.AlignHCenter)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(115, 20))
        self.comboBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_useModel = QtWidgets.QWidget()
        self.tab_useModel.setMinimumSize(QtCore.QSize(950, 600))
        self.tab_useModel.setObjectName("tab_useModel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_useModel)
        self.gridLayout_3.setContentsMargins(10, 25, 10, 25)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 6, 1, 1)
        self.pushButton_segmentation = QtWidgets.QPushButton(self.tab_useModel)
        self.pushButton_segmentation.setToolTip("Start Image Segmentation")
        self.pushButton_segmentation.setEnabled(False)
        self.pushButton_segmentation.setMinimumSize(QtCore.QSize(200, 25))
        self.pushButton_segmentation.setMaximumSize(QtCore.QSize(200, 25))
        self.pushButton_segmentation.setObjectName("pushButton_segmentation")
        self.gridLayout_3.addWidget(self.pushButton_segmentation, 1, 5, 1, 1)
        self.label_importImg = QtWidgets.QLabel(self.tab_useModel)
        self.label_importImg.setMinimumSize(QtCore.QSize(175, 25))
        self.label_importImg.setMaximumSize(QtCore.QSize(175, 25))
        self.label_importImg.setSizeIncrement(QtCore.QSize(175, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_importImg.setFont(font)
        self.label_importImg.setScaledContents(True)
        self.label_importImg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_importImg.setObjectName("label_importImg")
        self.gridLayout_3.addWidget(self.label_importImg, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem9, 4, 0, 1, 1)
        self.label_chooseModel = QtWidgets.QLabel(self.tab_useModel)
        self.label_chooseModel.setEnabled(False)
        self.label_chooseModel.setMinimumSize(QtCore.QSize(300, 25))
        self.label_chooseModel.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_chooseModel.setFont(font)
        self.label_chooseModel.setScaledContents(True)
        self.label_chooseModel.setObjectName("label_chooseModel")
        self.gridLayout_3.addWidget(self.label_chooseModel, 0, 3, 1, 1)
        self.comboBox_chooseModel = QtWidgets.QComboBox(self.tab_useModel)
        self.comboBox_chooseModel.setEnabled(False)
        self.comboBox_chooseModel.setMinimumSize(QtCore.QSize(300, 25))
        self.comboBox_chooseModel.setMaximumSize(QtCore.QSize(300, 25))
        self.comboBox_chooseModel.setObjectName("comboBox_chooseModel")
        self.comboBox_chooseModel.addItem("")
        self.comboBox_chooseModel.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_chooseModel, 1, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 1, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem11, 2, 3, 1, 1)
        self.pushButton_chooseImg = QtWidgets.QPushButton(self.tab_useModel)
        self.pushButton_chooseImg.setToolTip("Import image to segment")
        self.pushButton_chooseImg.setMinimumSize(QtCore.QSize(175, 25))
        self.pushButton_chooseImg.setMaximumSize(QtCore.QSize(175, 25))
        self.pushButton_chooseImg.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_chooseImg.setObjectName("pushButton_chooseImg")
        self.gridLayout_3.addWidget(self.pushButton_chooseImg, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.lineEdit_saveImg_seg = QtWidgets.QLineEdit(self.tab_useModel)
        self.lineEdit_saveImg_seg.setEnabled(False)
        self.lineEdit_saveImg_seg.setMinimumSize(QtCore.QSize(250, 25))
        self.lineEdit_saveImg_seg.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_saveImg_seg.setFont(font)
        self.lineEdit_saveImg_seg.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_saveImg_seg.setObjectName("lineEdit_saveImg_seg")
        self.horizontalLayout_2.addWidget(self.lineEdit_saveImg_seg)
        self.pushButton_saveImg = QtWidgets.QPushButton(self.tab_useModel)
        self.pushButton_saveImg.setEnabled(False)
        self.pushButton_saveImg.setMinimumSize(QtCore.QSize(125, 25))
        self.pushButton_saveImg.setMaximumSize(QtCore.QSize(125, 25))
        self.pushButton_saveImg.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.pushButton_saveImg.setObjectName("pushButton_saveImg")
        self.horizontalLayout_2.addWidget(self.pushButton_saveImg)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 6, 0, 1, 7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.scrollArea_ImgOrig = QtWidgets.QScrollArea(self.tab_useModel)
        self.scrollArea_ImgOrig.setToolTip("Original Image")
        self.scrollArea_ImgOrig.setMinimumSize(QtCore.QSize(350, 350))
        self.scrollArea_ImgOrig.setMaximumSize(QtCore.QSize(565, 584))
        self.scrollArea_ImgOrig.setSizeIncrement(QtCore.QSize(1, 1))
        self.scrollArea_ImgOrig.setBaseSize(QtCore.QSize(1, 1))
        self.scrollArea_ImgOrig.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_ImgOrig.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_ImgOrig.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_ImgOrig.setWidgetResizable(False)
        self.scrollArea_ImgOrig.setObjectName("scrollArea_ImgOrig")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 422, 414))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_ImgOrig.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout.addWidget(self.scrollArea_ImgOrig)
        self.scrollArea_ImgSeg = QtWidgets.QScrollArea(self.tab_useModel)
        self.scrollArea_ImgSeg.setToolTip("Segmented Image")
        self.scrollArea_ImgSeg.setMinimumSize(QtCore.QSize(350, 350))
        self.scrollArea_ImgSeg.setMaximumSize(QtCore.QSize(565, 584))
        self.scrollArea_ImgSeg.setSizeIncrement(QtCore.QSize(1, 1))
        self.scrollArea_ImgSeg.setBaseSize(QtCore.QSize(1, 1))
        self.scrollArea_ImgSeg.setWidgetResizable(False)
        self.scrollArea_ImgSeg.setObjectName("scrollArea_ImgSeg")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 422, 414))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.scrollArea_ImgSeg.setWidget(self.scrollAreaWidgetContents_8)
        self.horizontalLayout.addWidget(self.scrollArea_ImgSeg)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 7)
        self.tabWidget.addTab(self.tab_useModel, "")
        self.tab_buildModel = QtWidgets.QWidget()
        self.tab_buildModel.setMinimumSize(QtCore.QSize(950, 625))
        self.tab_buildModel.setObjectName("tab_buildModel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_buildModel)
        self.gridLayout_4.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem16 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem16, 2, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 1, 5, 1, 1)
        self.verticalLayout_buildModel = QtWidgets.QVBoxLayout()
        self.verticalLayout_buildModel.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_buildModel.setObjectName("verticalLayout_buildModel")
        spacerItem18 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_buildModel.addItem(spacerItem18)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 5, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_selectMethod = QtWidgets.QLabel(self.tab_buildModel)
        self.label_selectMethod.setMaximumSize(QtCore.QSize(260, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_selectMethod.setFont(font)
        self.label_selectMethod.setScaledContents(True)
        self.label_selectMethod.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_selectMethod.setObjectName("label_selectMethod")
        self.verticalLayout_3.addWidget(self.label_selectMethod)
        self.comboBox_selectMethod = QtWidgets.QComboBox(self.tab_buildModel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_selectMethod.sizePolicy().hasHeightForWidth())
        self.comboBox_selectMethod.setSizePolicy(sizePolicy)
        self.comboBox_selectMethod.setMaximumSize(QtCore.QSize(260, 25))
        self.comboBox_selectMethod.setObjectName("comboBox_selectMethod")
        self.comboBox_selectMethod.addItem("")
        self.comboBox_selectMethod.addItem("")
        self.comboBox_selectMethod.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_selectMethod)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, 0, -1, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_importDataset = QtWidgets.QLabel(self.tab_buildModel)
        self.label_importDataset.setEnabled(False)
        self.label_importDataset.setMinimumSize(QtCore.QSize(130, 25))
        self.label_importDataset.setMaximumSize(QtCore.QSize(140, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_importDataset.setFont(font)
        self.label_importDataset.setScaledContents(True)
        self.label_importDataset.setAlignment(QtCore.Qt.AlignCenter)
        self.label_importDataset.setObjectName("label_importDataset")
        self.verticalLayout_4.addWidget(self.label_importDataset)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_chooseDataset = QtWidgets.QPushButton(self.tab_buildModel)
        self.pushButton_chooseDataset.setToolTip("Import images to train and test the model")
        self.pushButton_chooseDataset.setEnabled(False)
        self.pushButton_chooseDataset.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_chooseDataset.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_chooseDataset.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_chooseDataset.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_chooseDataset.setIcon(icon)
        self.pushButton_chooseDataset.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_chooseDataset.setObjectName("pushButton_chooseDataset")
        self.horizontalLayout_3.addWidget(self.pushButton_chooseDataset)
        self.pushButton_chooseGT = QtWidgets.QPushButton(self.tab_buildModel)
        self.pushButton_chooseGT.setToolTip("Import GT images to train and test the model")
        self.pushButton_chooseGT.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.pushButton_chooseGT.sizePolicy().hasHeightForWidth())
        self.pushButton_chooseGT.setSizePolicy(sizePolicy)
        self.pushButton_chooseGT.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_chooseGT.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_chooseGT.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("21_manual1.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_chooseGT.setIcon(icon1)
        self.pushButton_chooseGT.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_chooseGT.setObjectName("pushButton_chooseGT")
        self.horizontalLayout_3.addWidget(self.pushButton_chooseGT)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout_buildModel.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_newModelName = QtWidgets.QLabel(self.tab_buildModel)
        self.label_newModelName.setEnabled(False)
        self.label_newModelName.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_newModelName.setFont(font)
        self.label_newModelName.setToolTip("")
        self.label_newModelName.setScaledContents(True)
        self.label_newModelName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_newModelName.setObjectName("label_newModelName")
        self.verticalLayout_7.addWidget(self.label_newModelName)
        self.lineEdit_newModelName = QtWidgets.QLineEdit(self.tab_buildModel)
        self.lineEdit_newModelName.setEnabled(False)
        self.lineEdit_newModelName.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_newModelName.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_newModelName.setFont(font)
        self.lineEdit_newModelName.setObjectName("lineEdit_newModelName")
        self.verticalLayout_7.addWidget(self.lineEdit_newModelName)
        self.horizontalLayout_16.addLayout(self.verticalLayout_7)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.pushButton_train = QtWidgets.QPushButton(self.tab_buildModel)
        self.pushButton_train.setToolTip("Start training and testing your model")
        self.pushButton_train.setEnabled(False)
        self.pushButton_train.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_train.setObjectName("pushButton_train")
        self.horizontalLayout_16.addWidget(self.pushButton_train)
        self.verticalLayout_buildModel.addLayout(self.horizontalLayout_16)
        spacerItem21 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_buildModel.addItem(spacerItem21)
        self.gridLayout_4.addLayout(self.verticalLayout_buildModel, 1, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem22, 2, 10, 1, 1)
        self.verticalLayout_testMetrics = QtWidgets.QVBoxLayout()
        self.verticalLayout_testMetrics.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_testMetrics.setSpacing(0)
        self.verticalLayout_testMetrics.setObjectName("verticalLayout_testMetrics")
        spacerItem23 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_testMetrics.addItem(spacerItem23)
        self.label_testMetrics = QtWidgets.QLabel(self.tab_buildModel)
        self.label_testMetrics.setEnabled(False)
        self.label_testMetrics.setMinimumSize(QtCore.QSize(150, 25))
        self.label_testMetrics.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_testMetrics.setFont(font)
        self.label_testMetrics.setScaledContents(True)
        self.label_testMetrics.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_testMetrics.setObjectName("label_testMetrics")
        self.verticalLayout_testMetrics.addWidget(self.label_testMetrics)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_Acc_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_Acc_2.setEnabled(False)
        self.label_Acc_2.setMinimumSize(QtCore.QSize(65, 20))
        self.label_Acc_2.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Acc_2.setFont(font)
        self.label_Acc_2.setScaledContents(True)
        self.label_Acc_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Acc_2.setObjectName("label_Acc_2")
        self.horizontalLayout_11.addWidget(self.label_Acc_2)
        self.label_printAcc_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printAcc_2.setEnabled(False)
        self.label_printAcc_2.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printAcc_2.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printAcc_2.setFont(font)
        self.label_printAcc_2.setText("")
        self.label_printAcc_2.setObjectName("label_printAcc_2")
        self.horizontalLayout_11.addWidget(self.label_printAcc_2)
        self.verticalLayout_testMetrics.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_AUC_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_AUC_2.setEnabled(False)
        self.label_AUC_2.setMinimumSize(QtCore.QSize(65, 25))
        self.label_AUC_2.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_AUC_2.setFont(font)
        self.label_AUC_2.setObjectName("label_AUC_2")
        self.horizontalLayout_18.addWidget(self.label_AUC_2)
        self.label_printAUC_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printAUC_2.setEnabled(False)
        self.label_printAUC_2.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printAUC_2.setMaximumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printAUC_2.setFont(font)
        self.label_printAUC_2.setText("")
        self.label_printAUC_2.setObjectName("label_printAUC_2")
        self.horizontalLayout_18.addWidget(self.label_printAUC_2)
        self.verticalLayout_testMetrics.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_Precision_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_Precision_2.setEnabled(False)
        self.label_Precision_2.setMinimumSize(QtCore.QSize(65, 25))
        self.label_Precision_2.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Precision_2.setFont(font)
        self.label_Precision_2.setScaledContents(True)
        self.label_Precision_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Precision_2.setObjectName("label_Precision_2")
        self.horizontalLayout_12.addWidget(self.label_Precision_2)
        self.label_printPrecision_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printPrecision_2.setEnabled(False)
        self.label_printPrecision_2.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printPrecision_2.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printPrecision_2.setFont(font)
        self.label_printPrecision_2.setText("")
        self.label_printPrecision_2.setObjectName("label_printPrecision_2")
        self.horizontalLayout_12.addWidget(self.label_printPrecision_2)
        self.verticalLayout_testMetrics.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_Recall_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_Recall_2.setEnabled(False)
        self.label_Recall_2.setMinimumSize(QtCore.QSize(65, 25))
        self.label_Recall_2.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Recall_2.setFont(font)
        self.label_Recall_2.setScaledContents(True)
        self.label_Recall_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Recall_2.setObjectName("label_Recall_2")
        self.horizontalLayout_13.addWidget(self.label_Recall_2)
        self.label_printRecall_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printRecall_2.setEnabled(False)
        self.label_printRecall_2.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printRecall_2.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printRecall_2.setFont(font)
        self.label_printRecall_2.setText("")
        self.label_printRecall_2.setObjectName("label_printRecall_2")
        self.horizontalLayout_13.addWidget(self.label_printRecall_2)
        self.verticalLayout_testMetrics.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_DICE_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_DICE_2.setEnabled(False)
        self.label_DICE_2.setMinimumSize(QtCore.QSize(65, 25))
        self.label_DICE_2.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_DICE_2.setFont(font)
        self.label_DICE_2.setScaledContents(True)
        self.label_DICE_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_DICE_2.setObjectName("label_DICE_2")
        self.horizontalLayout_14.addWidget(self.label_DICE_2)
        self.label_printDICE_2 = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printDICE_2.setEnabled(False)
        self.label_printDICE_2.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printDICE_2.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printDICE_2.setFont(font)
        self.label_printDICE_2.setText("")
        self.label_printDICE_2.setObjectName("label_printDICE_2")
        self.horizontalLayout_14.addWidget(self.label_printDICE_2)
        self.verticalLayout_testMetrics.addLayout(self.horizontalLayout_14)
        spacerItem24 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_testMetrics.addItem(spacerItem24)
        self.gridLayout_4.addLayout(self.verticalLayout_testMetrics, 1, 9, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem25, 1, 10, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem26, 1, 3, 1, 1)
        self.verticalLayout_metricsTrain = QtWidgets.QVBoxLayout()
        self.verticalLayout_metricsTrain.setContentsMargins(0, 0, 4, 0)
        self.verticalLayout_metricsTrain.setSpacing(0)
        self.verticalLayout_metricsTrain.setObjectName("verticalLayout_metricsTrain")
        spacerItem27 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_metricsTrain.addItem(spacerItem27)
        self.label_trainMetrics = QtWidgets.QLabel(self.tab_buildModel)
        self.label_trainMetrics.setEnabled(False)
        self.label_trainMetrics.setMinimumSize(QtCore.QSize(150, 25))
        self.label_trainMetrics.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_trainMetrics.setFont(font)
        self.label_trainMetrics.setScaledContents(True)
        self.label_trainMetrics.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_trainMetrics.setObjectName("label_trainMetrics")
        self.verticalLayout_metricsTrain.addWidget(self.label_trainMetrics)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_Acc = QtWidgets.QLabel(self.tab_buildModel)
        self.label_Acc.setEnabled(False)
        self.label_Acc.setMinimumSize(QtCore.QSize(65, 25))
        self.label_Acc.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Acc.setFont(font)
        self.label_Acc.setScaledContents(True)
        self.label_Acc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Acc.setObjectName("label_Acc")
        self.horizontalLayout_7.addWidget(self.label_Acc)
        self.label_printAcc = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printAcc.setEnabled(False)
        self.label_printAcc.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printAcc.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printAcc.setFont(font)
        self.label_printAcc.setText("")
        self.label_printAcc.setObjectName("label_printAcc")
        self.horizontalLayout_7.addWidget(self.label_printAcc)
        self.verticalLayout_metricsTrain.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_AUC = QtWidgets.QLabel(self.tab_buildModel)
        self.label_AUC.setEnabled(False)
        self.label_AUC.setMinimumSize(QtCore.QSize(65, 25))
        self.label_AUC.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_AUC.setFont(font)
        self.label_AUC.setObjectName("label_AUC")
        self.horizontalLayout_17.addWidget(self.label_AUC)
        self.label_printAUC = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printAUC.setEnabled(False)
        self.label_printAUC.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printAUC.setMaximumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printAUC.setFont(font)
        self.label_printAUC.setText("")
        self.label_printAUC.setObjectName("label_printAUC")
        self.horizontalLayout_17.addWidget(self.label_printAUC)
        self.verticalLayout_metricsTrain.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_Precision = QtWidgets.QLabel(self.tab_buildModel)
        self.label_Precision.setEnabled(False)
        self.label_Precision.setMinimumSize(QtCore.QSize(65, 25))
        self.label_Precision.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Precision.setFont(font)
        self.label_Precision.setScaledContents(True)
        self.label_Precision.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Precision.setObjectName("label_Precision")
        self.horizontalLayout_8.addWidget(self.label_Precision)
        self.label_printPrecision = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printPrecision.setEnabled(False)
        self.label_printPrecision.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printPrecision.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printPrecision.setFont(font)
        self.label_printPrecision.setText("")
        self.label_printPrecision.setObjectName("label_printPrecision")
        self.horizontalLayout_8.addWidget(self.label_printPrecision)
        self.verticalLayout_metricsTrain.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_Recall = QtWidgets.QLabel(self.tab_buildModel)
        self.label_Recall.setEnabled(False)
        self.label_Recall.setMinimumSize(QtCore.QSize(65, 25))
        self.label_Recall.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Recall.setFont(font)
        self.label_Recall.setScaledContents(True)
        self.label_Recall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Recall.setObjectName("label_Recall")
        self.horizontalLayout_9.addWidget(self.label_Recall)
        self.label_printRecall = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printRecall.setEnabled(False)
        self.label_printRecall.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printRecall.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printRecall.setFont(font)
        self.label_printRecall.setText("")
        self.label_printRecall.setObjectName("label_printRecall")
        self.horizontalLayout_9.addWidget(self.label_printRecall)
        self.verticalLayout_metricsTrain.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_DICE = QtWidgets.QLabel(self.tab_buildModel)
        self.label_DICE.setEnabled(False)
        self.label_DICE.setMinimumSize(QtCore.QSize(65, 25))
        self.label_DICE.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_DICE.setFont(font)
        self.label_DICE.setScaledContents(True)
        self.label_DICE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_DICE.setObjectName("label_DICE")
        self.horizontalLayout_10.addWidget(self.label_DICE)
        self.label_printDICE = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printDICE.setEnabled(False)
        self.label_printDICE.setMinimumSize(QtCore.QSize(60, 25))
        self.label_printDICE.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_printDICE.setFont(font)
        self.label_printDICE.setText("")
        self.label_printDICE.setObjectName("label_printDICE")
        self.horizontalLayout_10.addWidget(self.label_printDICE)
        self.verticalLayout_metricsTrain.addLayout(self.horizontalLayout_10)
        spacerItem28 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_metricsTrain.addItem(spacerItem28)
        self.gridLayout_4.addLayout(self.verticalLayout_metricsTrain, 1, 6, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem29, 4, 6, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem30, 1, 1, 1, 1)
        self.verticalLayout_trainTime = QtWidgets.QVBoxLayout()
        self.verticalLayout_trainTime.setObjectName("verticalLayout_trainTime")
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_trainTime.addItem(spacerItem31)
        self.label_trainTime = QtWidgets.QLabel(self.tab_buildModel)
        self.label_trainTime.setEnabled(False)
        self.label_trainTime.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_trainTime.setFont(font)
        self.label_trainTime.setScaledContents(True)
        self.label_trainTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_trainTime.setObjectName("label_trainTime")
        self.verticalLayout_trainTime.addWidget(self.label_trainTime)
        self.label_printTrainTime = QtWidgets.QLabel(self.tab_buildModel)
        self.label_printTrainTime.setEnabled(False)
        self.label_printTrainTime.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_printTrainTime.setFont(font)
        self.label_printTrainTime.setText("")
        self.label_printTrainTime.setObjectName("label_printTrainTime")
        self.verticalLayout_trainTime.addWidget(self.label_printTrainTime)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_trainTime.addItem(spacerItem32)
        self.gridLayout_4.addLayout(self.verticalLayout_trainTime, 1, 11, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem33, 1, 12, 1, 1)
        self.horizontalLayout_segmentAImage = QtWidgets.QHBoxLayout()
        self.horizontalLayout_segmentAImage.setSpacing(0)
        self.horizontalLayout_segmentAImage.setObjectName("horizontalLayout_segmentAImage")
        spacerItem34 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_segmentAImage.addItem(spacerItem34)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem35)
        self.label_ChooseImgTest = QtWidgets.QLabel(self.tab_buildModel)
        self.label_ChooseImgTest.setEnabled(False)
        self.label_ChooseImgTest.setMaximumSize(QtCore.QSize(100, 175))
        self.label_ChooseImgTest.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ChooseImgTest.setWordWrap(True)
        self.label_ChooseImgTest.setObjectName("label_ChooseImgTest")
        self.verticalLayout_10.addWidget(self.label_ChooseImgTest)
        self.pushButton_ImportImgTrain = QtWidgets.QPushButton(self.tab_buildModel)
        self.pushButton_ImportImgTrain.setToolTip("Import image from the training dataset")
        self.pushButton_ImportImgTrain.setEnabled(False)
        self.pushButton_ImportImgTrain.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_ImportImgTrain.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_ImportImgTrain.setObjectName("pushButton_ImportImgTrain")
        self.verticalLayout_10.addWidget(self.pushButton_ImportImgTrain)
        self.pushButton_ImportImgTest = QtWidgets.QPushButton(self.tab_buildModel)
        self.pushButton_ImportImgTest.setToolTip("Import image from the testing dataset")
        self.pushButton_ImportImgTest.setEnabled(False)
        self.pushButton_ImportImgTest.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_ImportImgTest.setObjectName("pushButton_ImportImgTest")
        self.verticalLayout_10.addWidget(self.pushButton_ImportImgTest)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem36)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem37)
        self.horizontalLayout_segmentAImage.addLayout(self.verticalLayout_10)
        spacerItem38 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_segmentAImage.addItem(spacerItem38)
        self.scrollArea_GT = QtWidgets.QScrollArea(self.tab_buildModel)
        self.scrollArea_GT.setToolTip("GT Image")
        self.scrollArea_GT.setMinimumSize(QtCore.QSize(350, 350))
        self.scrollArea_GT.setMaximumSize(QtCore.QSize(565, 584))
        self.scrollArea_GT.setSizeIncrement(QtCore.QSize(1, 1))
        self.scrollArea_GT.setBaseSize(QtCore.QSize(1, 1))
        self.scrollArea_GT.setWidgetResizable(False)
        self.scrollArea_GT.setObjectName("scrollArea_GT")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 396, 348))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_GT.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_segmentAImage.addWidget(self.scrollArea_GT)
        self.scrollArea_ImgSegBuild = QtWidgets.QScrollArea(self.tab_buildModel)
        self.scrollArea_ImgSegBuild.setToolTip("Segmented Image")
        self.scrollArea_ImgSegBuild.setMinimumSize(QtCore.QSize(350, 350))
        self.scrollArea_ImgSegBuild.setMaximumSize(QtCore.QSize(565, 584))
        self.scrollArea_ImgSegBuild.setSizeIncrement(QtCore.QSize(1, 1))
        self.scrollArea_ImgSegBuild.setBaseSize(QtCore.QSize(1, 1))
        self.scrollArea_ImgSegBuild.setWidgetResizable(False)
        self.scrollArea_ImgSegBuild.setObjectName("scrollArea_ImgSegBuild")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 396, 348))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_ImgSegBuild.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_segmentAImage.addWidget(self.scrollArea_ImgSegBuild)
        spacerItem39 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_segmentAImage.addItem(spacerItem39)
        self.gridLayout_4.addLayout(self.horizontalLayout_segmentAImage, 3, 0, 1, 13)
        self.horizontalLayout_saveModel = QtWidgets.QHBoxLayout()
        self.horizontalLayout_saveModel.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_saveModel.setSpacing(10)
        self.horizontalLayout_saveModel.setObjectName("horizontalLayout_saveModel")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_saveModel.addItem(spacerItem40)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_saveModel.addItem(spacerItem41)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_saveModel.addItem(spacerItem42)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_saveModel.addItem(spacerItem43)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_saveModel.addItem(spacerItem44)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_saveModel.addItem(spacerItem45)
        self.pushButton_saveModel = QtWidgets.QPushButton(self.tab_buildModel)
        self.pushButton_saveModel.setEnabled(False)
        self.pushButton_saveModel.setMaximumSize(QtCore.QSize(150, 150))
        self.pushButton_saveModel.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.pushButton_saveModel.setObjectName("pushButton_saveModel")
        self.horizontalLayout_saveModel.addWidget(self.pushButton_saveModel)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_saveModel.addItem(spacerItem46)
        self.gridLayout_4.addLayout(self.horizontalLayout_saveModel, 12, 3, 1, 10)
        self.tabWidget.addTab(self.tab_buildModel, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 22))
        self.menubar.setObjectName("menubar")
        self.menuRetina = QtWidgets.QMenu(self.menubar)
        self.menuRetina.setObjectName("menuRetina")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.statusbar.setPalette(palette)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionModelsInformation = QtWidgets.QAction(MainWindow)
        self.actionModelsInformation.setObjectName("actionModelsInformation")
        self.actionFitWindow = QtWidgets.QAction(MainWindow)
        self.actionFitWindow.setObjectName("actionFitWindow")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        self.actionZoomIn.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.action125 = QtWidgets.QAction(MainWindow)
        self.action125.setObjectName("action125")
        self.action150 = QtWidgets.QAction(MainWindow)
        self.action150.setObjectName("action150")
        self.action175 = QtWidgets.QAction(MainWindow)
        self.action175.setObjectName("action175")
        self.action200 = QtWidgets.QAction(MainWindow)
        self.action200.setObjectName("action200")
        self.actionRESET = QtWidgets.QAction(MainWindow)
        self.actionRESET.setObjectName("actionRESET")
        self.actionDraw_Window = QtWidgets.QAction(MainWindow)
        self.actionDraw_Window.setObjectName("actionDraw_Window")
        self.menuRetina.addSeparator()
        self.menubar.addAction(self.menuRetina.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)
        self.comboBox_chooseModel.setCurrentIndex(-1)
        self.comboBox_selectMethod.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RetinaPlus - The Ultimate App for Retina Analysis"))
        self.label_title.setText(_translate("MainWindow", "RetinaPlus – The Ultimate App for Retina Analysis"))
        self.label_question.setText(_translate("MainWindow", "Select app use"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Use Model"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Build Model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Launch"))
        self.pushButton_segmentation.setText(_translate("MainWindow", "Ready for segmentation!"))
        self.label_importImg.setText(_translate("MainWindow", "Import Image"))
        self.label_chooseModel.setText(_translate("MainWindow", "Select Model"))
        self.comboBox_chooseModel.setItemText(0, _translate("MainWindow", "SVM_linear"))
        self.comboBox_chooseModel.setItemText(1, _translate("MainWindow", "SVM_RBF"))
        self.pushButton_chooseImg.setText(_translate("MainWindow", "Import from computer "))
        self.lineEdit_saveImg_seg.setText(_translate("MainWindow", "Name your image"))
        self.pushButton_saveImg.setToolTip(_translate("MainWindow", "<html><head/><body><p>click to save segmented image</p></body></html>"))
        self.pushButton_saveImg.setText(_translate("MainWindow", "Save image!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_useModel), _translate("MainWindow", "Use Model"))
        self.label_selectMethod.setText(_translate("MainWindow", "Select Classifier"))
        self.comboBox_selectMethod.setItemText(0, _translate("MainWindow", "Support Vector Machine"))
        self.comboBox_selectMethod.setItemText(1, _translate("MainWindow", "Random Decision Forests"))
        self.comboBox_selectMethod.setItemText(2, _translate("MainWindow", "Extremely Randomized Trees"))
        self.label_importDataset.setText(_translate("MainWindow", "Import Dataset"))
        self.label_newModelName.setText(_translate("MainWindow", "Model Name"))
        self.lineEdit_newModelName.setText(_translate("MainWindow", "Name your model"))
        self.pushButton_train.setText(_translate("MainWindow", "Train!"))
        self.label_testMetrics.setText(_translate("MainWindow", "Test Metrics"))
        self.label_Acc_2.setText(_translate("MainWindow", "Acc:"))
        self.label_AUC_2.setText(_translate("MainWindow", "AUC:"))
        self.label_Precision_2.setText(_translate("MainWindow", "Precision:"))
        self.label_Recall_2.setText(_translate("MainWindow", "Recall:"))
        self.label_DICE_2.setText(_translate("MainWindow", "DICE:"))
        self.label_trainMetrics.setText(_translate("MainWindow", "Train Metrics"))
        self.label_Acc.setText(_translate("MainWindow", "Acc:"))
        self.label_AUC.setText(_translate("MainWindow", "AUC:"))
        self.label_Precision.setText(_translate("MainWindow", "Precision:"))
        self.label_Recall.setText(_translate("MainWindow", "Recall:"))
        self.label_DICE.setText(_translate("MainWindow", "DICE:"))
        self.label_trainTime.setText(_translate("MainWindow", "Train Time"))
        self.label_ChooseImgTest.setText(_translate("MainWindow", "Select an image from the imported dataset to show segmentation result"))
        self.pushButton_ImportImgTrain.setText(_translate("MainWindow", "Train"))
        self.pushButton_ImportImgTest.setText(_translate("MainWindow", "Test"))
        self.pushButton_saveModel.setToolTip(_translate("MainWindow", "<html><head/><body><p>click to save your model</p></body></html>"))
        self.pushButton_saveModel.setText(_translate("MainWindow", "Save model!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_buildModel), _translate("MainWindow", "Build Model"))
        self.menuRetina.setTitle(_translate("MainWindow", "Menu"))
        self.actionModelsInformation.setText(_translate("MainWindow", "Models Information"))
        self.actionFitWindow.setText(_translate("MainWindow", "Fit Window"))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.action125.setText(_translate("MainWindow", "125%"))
        self.action150.setText(_translate("MainWindow", "150%"))
        self.action175.setText(_translate("MainWindow", "175%"))
        self.action200.setText(_translate("MainWindow", "200%"))
        self.actionRESET.setText(_translate("MainWindow", "RESET"))
        self.actionDraw_Window.setText(_translate("MainWindow", "Draw Window"))
